### ISSUE TITLE
rtop Fatal error: exception Fl_package_base.No_such_package("threads.posix", "required by `utop'")

### ISSUE THREAD

**Issue by taigua** [facebook/reason#1706]
My environment:
OS: Debian sid 64bit
nodejs: 8.9.3
npm: 5.6.0

I install reason through: 
```bash
$ npm install -g https://github.com/reasonml/reason-cli/archive/3.0.4-bin-linux.tar.gz
```
After installation:
```bash
$ refmt --version
Reason 3.0.4 @ 731e605
$ ocamlmerlin -version
The Merlin toolkit version 2.5.4, for Ocaml 4.02.3
```
It seems OK. But when I use rtop, it complains:
```bash
$ rtop
Fatal error: exception Fl_package_base.No_such_package("threads.posix", "required by `utop'")
$ utop
Fatal error: exception Fl_package_base.No_such_package("threads.posix", "required by `utop'")

```

May anyone help?  Thanks.

**Comment by andreypopp** [comment]
I've tried and was able to repro, also `ocamlfind list` is missing `threads.posix`.

I've tried to build a new release on Linux using `esy@0.0.54` and it worked well. @jordwalke is that a problem with a host you've used to build a Linux release?

**Comment by jordwalke** [comment]
@andreypopp I used esy version `0.52` to build that release. Did anything change with stublibs that might have effected thing (since fixed in the latest releases)?

**Comment by andreypopp** [comment]
Not sure if it relate to `stublibs` — `ocamlfind list` just doesn't list `threads.posix`.

I've tried to build a release on Linux image from Travis using `esy@0.0.52` and it worked correctly.

**Comment by jordwalke** [comment]
I pushed a new release for linux. Not sure what went wrong during the last release. It seems to work for me now. Let me know if you see different.

**Comment by taigua** [comment]
@jordwalke, Thanks for help. but it still complained:
```bash
$ rtop
Fatal error: exception Fl_package_base.No_such_package("threads.posix", "required by `utop'")
$ utop
Fatal error: exception Fl_package_base.No_such_package("threads.posix", "required by `utop'")
```

It's wired, so I rolled back to v3.0.1. It works well.
Thanks all the same.

**Comment by jordwalke** [comment]
That's strange because I could repro, then I fixed it and with my fix I could not repro so it makes me think I actually fixed it. Can you try `npm remove -g reason-cli` then reinstalling?

**Comment by taigua** [comment]
I trid to remove it through ```npm remove -g reason-cli```, but it complained:
```
npm ERR! code E404
npm ERR! 404 Not Found: reason-cli@^3.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-16T08_31_33_998Z-debug.log
```
May be due to reason-cli doesn't on npmjs (I guess)
So I remove manully by
```bash
$ rm -rf /usr/lib/node_modules/reason-cli
```
And then
```bash
$ npm install -g https://github.com/reasonml/reason-cli/archive/3.0.4-bin-linux.tar.gz
$ rtop
Fatal error: exception Fl_package_base.No_such_package("threads.posix", "required by `utop'")
```
Still broken. :(

**Comment by thangngoc89** [comment]
I can confirm this. Upgraded to 3.0.4 and this is broken

**Comment by jordwalke** [comment]
We have discovered the issue. We will make a new release soon which addresses it. cc @andreypopp

**Comment by jordwalke** [comment]
Could you please try again when you get a chance?
Make sure to `npm remove -g reason-cli` before reinstalling.

**Comment by thangngoc89** [comment]
How do I do it? There is no new releases in reason-cli

**Comment by jordwalke** [comment]
@thangngoc89 It's the same release version/link. I just updated it. So uninstall `npm remove -g reason-cli` and then reinstall according to the instructions.

**Comment by thangngoc89** [comment]
Oh. Sneaky. Will install it when I come back to computer

**Comment by taigua** [comment]
@jordwalke Oh yeah, it works. Awesome.
Thank you, Jordan. You're very nice.

**Comment by mroch** [comment]
> We have discovered the issue. We will make a new release soon which addresses it. cc @andreypopp

![image](https://user-images.githubusercontent.com/3012/116326727-1e945200-a793-11eb-800c-cb35bae32425.png)

**Comment by scemama** [comment]
> We have discovered the issue. We will make a new release soon which addresses it. cc @andreypopp

Could you please explain where the problem came from, and how you addressed it? Thanks!
