### ISSUE TITLE
regressions  when upgrade in bucklescript 7

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#2502]
- [ ] https://github.com/BuckleScript/bucklescript/issues/3987

- [x] https://github.com/BuckleScript/bucklescript/issues/3969

- [ ] https://github.com/facebook/reason/issues/2493

**Comment by bobzhang** [comment]
@anmonteiro can you reopen it since not all of them are fixed?

**Comment by anmonteiro** [comment]
@bobzhang what's not fixed? As I said in https://github.com/facebook/reason/issues/2499#issuecomment-559883108, the JSX PPX is not maintained in this repo anymore.

**Comment by bobzhang** [comment]
@anmonteiro thanks, I will ping @rickyvetter
