### ISSUE TITLE
installation fails on osx 10.10 

### ISSUE THREAD

**Issue by ashee** [facebook/reason#468]
```
amitava:~ amitava$ opam pin add -y reason https://github.com/facebook/reason.git#0.0.5
[NOTE] Package reason is already git-pinned to https://github.com/facebook/reason.git#0.0.5.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[reason] https://github.com/facebook/reason.git#0.0.5 updated
[reason] Installing new package description from https://github.com/facebook/reason.git#0.0.5

reason needs to be installed.
The following dependencies couldn't be met:
  - reason -> menhir >= 20160303
Your request can't be satisfied:
  - No package matches menhir>=20160303.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

#  Environment
## OS
```
amitava:~ amitava$ uname -a
Darwin amitava.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
```
From About this mac, 
OSX Yosemite 
Version: 10.10.5 (14F1713)

# Detailed installation log
```
$ brew install opam
==> Installing dependencies for opam: ocaml, ocamlbuild, camlp4
==> Installing opam dependency: ocaml
==> Downloading https://homebrew.bintray.com/bottles/ocaml-4.03.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ocaml-4.03.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/ocaml/4.03.0: 1,641 files, 173.7M
==> Installing opam dependency: ocamlbuild
==> Downloading https://homebrew.bintray.com/bottles/ocamlbuild-0.9.2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ocamlbuild-0.9.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/ocamlbuild/0.9.2: 26 files, 6.6M
==> Installing opam dependency: camlp4
==> Downloading https://homebrew.bintray.com/bottles/camlp4-4.03+1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring camlp4-4.03+1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/camlp4/4.03+1: 164 files, 142.2M
==> Installing opam
==> Downloading https://homebrew.bintray.com/bottles/opam-1.2.2_2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring opam-1.2.2_2.yosemite.bottle.tar.gz
==> Caveats
OPAM uses ~/.opam by default for its package database, so you need to
initialize it first by running (as a normal user):

$  opam init

Run the following to initialize your environment variables:

$  eval `opam config env`

To export the needed variables every time, add them to your dotfiles.
  * On Bash, add them to `~/.bash_profile`.
  * On Zsh, add them to `~/.zprofile` or `~/.zshrc` instead.

Documentation and tutorials are available at https://opam.ocaml.org, or
via "man opam" and "opam --help".

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/opam/1.2.2_2: 30 files, 14.9M
$ opam init
OPAM has already been initialized.
In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

  - ~/.bash_profile (or a file you specify) to set the right environment
    variables and to load the auto-completion scripts for your shell (bash)
    on startup. Specifically, it checks for and appends the following line:

    . /Users/amitava/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true


  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`
    (i.e. those installed by OPAM) will work correctly when running the
    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
    of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

   opam config setup -a


Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.bash_profile)
    [N/y/f] y

User configuration:
  Updating ~/.ocamlinit.
  Updating ~/.bash_profile.
Global configuration:
  ~/.opam/opam-init/init.sh is already up-to-date.
  ~/.opam/opam-init/init.zsh is already up-to-date.
  ~/.opam/opam-init/init.csh is already up-to-date.
  ~/.opam/opam-init/init.fish is already up-to-date.
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
$ vim ~/.bash_profile
$ . ~/.bash_profile
$ clear
$ opam switch 4.02.3

=-=- Installing compiler 4.02.3 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default.comp] http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.3.tar.gz downloaded
Now compiling OCaml. This may take a while, please bear with us...
Processing: [4.02.3: make world.opt]
Done.

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
Done.
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
$
$ eval `opam config env`
$ clear
$ opam pin add -y merlin https://github.com/the-lambda-church/merlin.git#reason-0.0.1
merlin is now git-pinned to https://github.com/the-lambda-church/merlin.git#reason-0.0.1

[merlin] https://github.com/the-lambda-church/merlin.git#reason-0.0.1 updated
[merlin] Installing new package description from https://github.com/the-lambda-church/merlin.git#reason-0.0.1

merlin needs to be installed.
The following actions will be performed:
  ∗  install ocamlbuild  0                    [required by cppo]
  ∗  install ocamlfind   1.5.6                [required by merlin]
  ∗  install easy-format 1.2.0                [required by yojson]
  ∗  install cppo        1.3.1                [required by yojson]
  ∗  install biniou      1.0.9                [required by yojson]
  ∗  install yojson      1.2.3                [required by merlin]
  ∗  install merlin      2.3.1*
===== ∗  7 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[cppo] Archive in cache
[default] https://opam.ocaml.org/archives/easy-format.1.2.0+opam.tar.gz downloaded
[ocamlfind] Archive in cache
[default] https://opam.ocaml.org/archives/biniou.1.0.9+opam.tar.gz downloaded
[merlin] https://github.com/the-lambda-church/merlin.git#reason-0.0.1 already up-to-date
[default] https://opam.ocaml.org/archives/yojson.1.2.3+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed ocamlbuild.0
∗  installed ocamlfind.1.5.6
∗  installed easy-format.1.2.0
∗  installed biniou.1.0.9
∗  installed cppo.1.3.1
∗  installed yojson.1.2.3
∗  installed merlin.2.3.1
Done.

=-=- merlin.2.3.1 installed successfully =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
=> merlin installed.

   Quick setup for VIM
   -------------------
   Append this to your .vimrc to add merlin to vim's runtime-path:
     let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
     execute "set rtp+=" . g:opamshare . "/merlin/vim"

   Also run the following line in vim to index the documentation:
     :execute "helptags " . g:opamshare . "/merlin/vim/doc"

   Quick setup for EMACS
   -------------------
   Add opam emacs directory to your load-path by appending this to your .emacs:
     ;; Add opam emacs directory to the load-path
     (setq opam-share (substring (shell-command-to-string "opam config var share 2> /dev/null") 0 -1))
     (add-to-list 'load-path (concat opam-share "/emacs/site-lisp"))
     ;; Load merlin-mode
     (require 'merlin)
     ;; Start merlin on ocaml files
     (add-hook 'tuareg-mode-hook 'merlin-mode t)
     (add-hook 'caml-mode-hook 'merlin-mode t)

   Take a look at https://github.com/the-lambda-church/merlin for more information
$ clear
$ opam pin add -y merlin_extend https://github.com/let-def/merlin-extend.git#reason-0.0.1
Package merlin_extend does not exist, create as a NEW package ? [Y/n] y
merlin_extend is now git-pinned to https://github.com/let-def/merlin-extend.git#reason-0.0.1

[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 updated
[merlin_extend] Installing new package description from https://github.com/let-def/merlin-extend.git#reason-0.0.1

merlin_extend needs to be installed.
The following actions will be performed:
  ∗  install merlin_extend 0.2*

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed merlin_extend.0.2
Done.
$ opam pin add -y reason https://github.com/facebook/reason.git#0.0.5
Package reason does not exist, create as a NEW package ? [Y/n] y
reason is now git-pinned to https://github.com/facebook/reason.git#0.0.5

[reason] https://github.com/facebook/reason.git#0.0.5 updated
[reason] Installing new package description from https://github.com/facebook/reason.git#0.0.5

reason needs to be installed.
The following dependencies couldn't be met:
  - reason -> menhir >= 20160303
Your request can't be satisfied:
  - No package matches menhir>=20160303.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of sync.
$
```

**Comment by xorgy** [comment]
I'm having more or less the same issue on Linux. It can't satisfy Menhir>=20160303.

Is it possible that this needs to be built locally, and linked in?

**Comment by ashee** [comment]
I had to update and upgrade opam. 

```
amitava:archives amitava$ opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default] synchronized from https://opam.ocaml.org

=-=- Synchronizing development packages -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 already up-to-date
[merlin] https://github.com/the-lambda-church/merlin.git#reason-0.0.1 already up-to-date

Updates available for 4.02.3, apply them with 'opam upgrade':
===== ∗  4   ↻  4   ↗  3 =====
amitava:archives amitava$ opam upgrade
The following actions will be performed:
  ∗  install   conf-m4         1               [required by ocamlfind]
  ∗  install   conf-ncurses    1+system        [required by ocamlfind]
  ∗  install   base-ocamlbuild base
  ∗  install   conf-which      1               [required by biniou]
  ↗  upgrade   ocamlfind       1.5.6 to 1.6.2
  ↻  recompile ocamlbuild      0
  ↻  recompile easy-format     1.2.0           [uses ocamlfind]
  ↗  upgrade   cppo            1.3.1 to 1.3.2
  ↻  recompile biniou          1.0.9           [uses ocamlfind]
  ↗  upgrade   yojson          1.2.3 to 1.3.2
  ↻  recompile merlin          2.3.1*          [uses ocamlfind, yojson]
===== ∗  4   ↻  4   ↗  3 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default] https://opam.ocaml.org/archives/biniou.1.0.9+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/easy-format.1.2.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/cppo.1.3.2+opam.tar.gz downloaded
[merlin] https://github.com/the-lambda-church/merlin.git#reason-0.0.1 already up-to-date
[default] https://opam.ocaml.org/archives/yojson.1.2.3+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.5.6+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.6.2+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/yojson.1.3.2+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[WARNING] Directory /Users/amitava/.opam/4.02.3/share/merlin is not empty, not removing
⊘  removed   merlin.2.3.1
∗  installed base-ocamlbuild.base
∗  installed conf-ncurses.1+system
∗  installed conf-which.1
∗  installed conf-m4.1
⊘  removed   yojson.1.2.3
⊘  removed   biniou.1.0.9
⊘  removed   cppo.1.3.1
[WARNING] Directory /Users/amitava/.opam/4.02.3/lib/ocamlbuild is not empty, not removing
⊘  removed   ocamlbuild.0
∗  installed ocamlbuild.0
⊘  removed   easy-format.1.2.0
⊘  removed   ocamlfind.1.5.6
∗  installed ocamlfind.1.6.2
∗  installed easy-format.1.2.0
∗  installed biniou.1.0.9
∗  installed cppo.1.3.2
∗  installed yojson.1.3.2
∗  installed merlin.2.3.1
Done.

=-=- merlin.2.3.1 installed successfully =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
=> merlin installed.

   Quick setup for VIM
   -------------------
   Append this to your .vimrc to add merlin to vim's runtime-path:
     let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
     execute "set rtp+=" . g:opamshare . "/merlin/vim"

   Also run the following line in vim to index the documentation:
     :execute "helptags " . g:opamshare . "/merlin/vim/doc"

   Quick setup for EMACS
   -------------------
   Add opam emacs directory to your load-path by appending this to your .emacs:
     ;; Add opam emacs directory to the load-path
     (setq opam-share (substring (shell-command-to-string "opam config var share 2> /dev/null") 0 -1))
     (add-to-list 'load-path (concat opam-share "/emacs/site-lisp"))
     ;; Load merlin-mode
     (require 'merlin)
     ;; Start merlin on ocaml files
     (add-hook 'tuareg-mode-hook 'merlin-mode t)
     (add-hook 'caml-mode-hook 'merlin-mode t)

   Take a look at https://github.com/the-lambda-church/merlin for more information
amitava:archives amitava$ opam switch 4.02.3
amitava:archives amitava$ opam pin add -y merlin https://github.com/the-lambda-church/merlin.git#reason-0.0.1
[NOTE] Package merlin is already git-pinned to https://github.com/the-lambda-church/merlin.git#reason-0.0.1.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[merlin] https://github.com/the-lambda-church/merlin.git#reason-0.0.1 updated
[merlin] Installing new package description from https://github.com/the-lambda-church/merlin.git#reason-0.0.1

amitava:archives amitava$ opam pin add -y merlin_extend https://github.com/let-def/merlin-extend.git#reason-0.0.1
[NOTE] Package merlin_extend is already git-pinned to https://github.com/let-def/merlin-extend.git#reason-0.0.1.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 updated
[merlin_extend] Installing new package description from https://github.com/let-def/merlin-extend.git#reason-0.0.1

amitava:archives amitava$ opam pin add -y merlin_extend https://github.com/let-def/merlin-extend.git#reason-0.0.1
[NOTE] Package merlin_extend is already git-pinned to https://github.com/let-def/merlin-extend.git#reason-0.0.1.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 updated
[merlin_extend] Installing new package description from https://github.com/let-def/merlin-extend.git#reason-0.0.1

amitava:archives amitava$ opam pin add -y reason https://github.com/facebook/reason.git#0.0.5
[NOTE] Package reason is already git-pinned to https://github.com/facebook/reason.git#0.0.5.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[reason] https://github.com/facebook/reason.git#0.0.5 updated
[reason] Installing new package description from https://github.com/facebook/reason.git#0.0.5

reason needs to be installed.
The following actions will be performed:
  ∗  install camomile     0.8.5               [required by zed]
  ∗  install react        1.2.0               [required by utop]
  ∗  install menhir       20160504            [required by reason]
  ∗  install ppx_tools    5.0+4.02.0          [required by utop]
  ∗  install base-bytes   base                [required by re]
  ∗  install ANSITerminal 0.6.5               [required by BetterErrors]
  ∗  install zed          1.4                 [required by lambda-term]
  ∗  install re           1.5.0               [required by BetterErrors]
  ∗  install lwt          2.5.2               [required by utop]
  ∗  install BetterErrors 0.0.1               [required by reason]
  ∗  install lambda-term  1.10                [required by utop]
  ∗  install utop         1.19.2              [required by reason]
  ∗  install reason       0.0.2*
===== ∗  13 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default] https://opam.ocaml.org/archives/BetterErrors.0.0.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ANSITerminal.0.6.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/lambda-term.1.10+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/lwt.2.5.2+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ppx_tools.5.0+4.02.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/re.1.5.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/menhir.20160504+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/react.1.2.0+opam.tar.gz downloaded
[reason] https://github.com/facebook/reason.git#0.0.5 already up-to-date
[default] https://opam.ocaml.org/archives/utop.1.19.2+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/zed.1.4+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/camomile.0.8.5+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed base-bytes.base
∗  installed ppx_tools.5.0+4.02.0
∗  installed ANSITerminal.0.6.5
∗  installed react.1.2.0
∗  installed re.1.5.0
∗  installed BetterErrors.0.0.1
∗  installed lwt.2.5.2
∗  installed menhir.20160504
∗  installed camomile.0.8.5
∗  installed zed.1.4
∗  installed lambda-term.1.10
∗  installed utop.1.19.2
∗  installed reason.0.0.2
Done.
amitava:archives amitava$
```

**Comment by xorgy** [comment]
Yeah, basically two things were required to make it work:
  Make sure you have camlp4 installed on your system, or lut will fail to build.
  run an `opam update` and then install.

**Comment by jordwalke** [comment]
The first logs looked like it was installing 4.03. That's kind of strange.
Thanks for checking out `Reason` in any event. Are things working for you now?

**Comment by xorgy** [comment]
Unfortunately, it seems the example of putting `print_string "Hello world"` in Hello.re and running `rebuild Hello.native` doesn't work.

**Comment by yunxing** [comment]
@xorgy Use `rebuild Hello.native` instead.

`rebuild` is a thin wrapper over [ocamlbuild] (https://github.com/ocaml/ocamlbuild). When running rebuild, instead of specifying the build _prerequisite_ (in this case, `Hello.re`), we specify the build _target_ (in this case, `Hello.native`)

**Comment by jordwalke** [comment]
@xorgy how are you installing ocaml and the dependencies? Did you use OPAM or are you using brew or something like that. I've had people try the installation on a fresh setup, and no one has ever had `camlp4` not be installed so it raised some questions.

**Comment by thekidfrankensteinthrewinapond** [comment]
For me it fails to install merlin-extend:

```
[NOTE] Package merlin_extend is already git-pinned to
       https://github.com/let-def/merlin-extend.git#reason-0.0.1.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[merlin_extend: git]
[merlin_extend: git]
[merlin_extend: git]
[merlin_extend: git]
[merlin_extend: git]
[merlin_extend: git]
[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 updated
[merlin_extend] Installing new package description from
https://github.com/let-def/merlin-extend.git#reason-0.0.1

merlin_extend needs to be installed.
The following actions will be performed:
  ∗  install merlin_extend 0.2*

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[merlin_extend: git] Command started
[merlin_extend: git] Command started
[merlin_extend: git] Command started
[merlin_extend: git] Command started
[merlin_extend] https://github.com/let-def/merlin-extend.git#reason-0.0.1 already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[merlin_extend: make] Command started
[ERROR] The compilation of merlin_extend failed at "make".
[merlin_extend: ocamlfind remove] Command started

#=== ERROR while installing merlin_extend.0.2 =================================#
# opam-version         1.2.2
# os                   darwin
# command              make
# path                 /Users/matthew/.opam/system/build/merlin_extend.0.2
# compiler             system (4.03.0)
# exit-code            2
# env-file             /Users/matthew/.opam/system/build/merlin_extend.0.2/merlin_extend-62460-a71bb4.env
# stdout-file          /Users/matthew/.opam/system/build/merlin_extend.0.2/merlin_extend-62460-a71bb4.out
# stderr-file          /Users/matthew/.opam/system/build/merlin_extend.0.2/merlin_extend-62460-a71bb4.err
### stdout ###
# [...]
# ocamlfind ocamldep -native extend_driver.mli > ._ncdi/extend_driver.di
# ocamlfind ocamldep -native extend_main.mli > ._ncdi/extend_main.di
# ocamlfind ocamldep -native extend_helper.mli > ._ncdi/extend_helper.di
# ocamlfind ocamldep extend_driver.ml > ._d/extend_driver.d
# ocamlfind ocamldep extend_main.ml > ._d/extend_main.d
# ocamlfind ocamldep extend_helper.ml > ._d/extend_helper.d
# ocamlfind ocamldep extend_protocol.ml > ._d/extend_protocol.d
# ocamlfind ocamlopt -package compiler-libs -c -g extend_protocol.ml
# ocamlfind ocamlc -package compiler-libs -c -g extend_helper.mli
# ocamlfind ocamlopt -package compiler-libs -c -g extend_helper.ml
### stderr ###
# [...]
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml, /usr/local/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml, /usr/local/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml, /usr/local/lib/ocaml/compiler-libs
# File "extend_helper.ml", line 24, characters 37-58:
# Error: The constructor Asttypes.Const_string belongs to the variant type
#          Asttypes.constant
#        but a constructor was expected belonging to the variant type
#          Parsetree.constant
# make[1]: *** [extend_helper.cmx] Error 2
# make: *** [native-code-library] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install merlin_extend 0.2
No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of
       sync.

```

**Comment by xorgy** [comment]
@yunxing Sorry, the output is the same for both of them. I was just trying `rebuild Hello.re` in that terminal I copied just in case you folks had a typo in your README.md.

**Comment by xorgy** [comment]
@jordwalke On Arch Linux, ocaml and camlp4 are packaged separately.

**Comment by yunxing** [comment]
@thekidfrankensteinthrewinapond It looks like you are using 4.03, could you try it again with a 4.02.3 switch?

**Comment by yunxing** [comment]
@thekidfrankensteinthrewinapond I tried 4.03 and got the same error. I think we need to tighten the version constraint until @kayceesrk's 4.03 compatibility effort get merged.

**Comment by xorgy** [comment]
For the record, not working for me on 4.02.3.

```
 ~ ocamlc -v
The OCaml compiler, version 4.02.3
Standard library directory: /usr/lib/ocaml

```

**Comment by yunxing** [comment]
Fixed @thekidfrankensteinthrewinapond (that id...)'s issue in #501 
Tracked @xorgy (much easier to remember!)'s issue in #500  

Closing this

**Comment by thekidfrankensteinthrewinapond** [comment]
Thank you!

**Comment by ryoia** [comment]
I followed the installation steps on the readme, switched to 4.02.3, still getting the same error for merlin and merlin_extend. I also ran `opam update` a few times already:

```
~ % opam switch 4.02.3                                                                   
~ % eval $(opam config env)
~ % opam pin add -y merlin 'https://github.com/the-lambda-church/merlin.git#reason-0.0.1'
[NOTE] Package merlin is already git-pinned to https://github.com/the-lambda-church/merlin.git#reason-0.0.1.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[merlin] https://github.com/the-lambda-church/merlin.git#reason-0.0.1 updated
[merlin] Installing new package description from https://github.com/the-lambda-church/merlin.git#reason-0.0.1

merlin needs to be installed.
The following actions will be performed:
  ∗  install ocamlbuild  0                    [required by cppo]
  ∗  install conf-m4     1                    [required by ocamlfind]
  ∗  install conf-which  1                    [required by biniou]
  ∗  install ocamlfind   1.6.2                [required by merlin]
  ∗  install easy-format 1.2.0                [required by yojson]
  ∗  install cppo        1.4.0                [required by yojson]
  ∗  install biniou      1.0.12               [required by yojson]
  ∗  install yojson      1.3.2                [required by merlin]
  ∗  install merlin      2.3.1*
===== ∗  9 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[biniou] Archive in cache
[cppo] Archive in cache
[easy-format] Archive in cache
[ocamlfind] Archive in cache
[yojson] Archive in cache
[ERROR] The sources of the following couldn't be obtained, aborting:
          - merlin.2.3.1
        (This may be fixed by running 'opam update')
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by jordwalke** [comment]
Also, if you install via `npm` using the [ExampleProject](https://github.com/reasonml/ExampleProject) these kind of errors should be highly unlikely because the project ensures that all d are modeled correctly.
